// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RekrutacjaNetPcCRUD.Model.Entities
{
    public partial class ContactCategory
    {
        public ContactCategory()
        {
            ContactSubcategory = new HashSet<ContactSubcategory>();
            Contacts = new HashSet<Contacts>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }

        [InverseProperty("Category")]
        public virtual ICollection<ContactSubcategory> ContactSubcategory { get; set; }
        [InverseProperty("Category")]
        public virtual ICollection<Contacts> Contacts { get; set; }
    }
}