// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RekrutacjaNetPcCRUD.Model.Entities
{
    public partial class ContactSubcategory
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }

        public virtual ContactCategory Category { get; set; }
    }
}