// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RekrutacjaNetPcCRUD.Model.Entities
{
    public partial class ContactCategory
    {
        public ContactCategory()
        {
            Contacts = new HashSet<Contacts>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Contacts> Contacts { get; set; }
    }
}