// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RekrutacjaNetPcCRUD.Model.Entities
{
    public partial class Contacts
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Password { get; set; }
        public int CatgoryId { get; set; }

        public virtual ContactCategory Catgory { get; set; }
    }
}