// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using RekrutacjaNetPcCRUD.Model.Entities;

namespace RekrutacjaNetPcCRUD.Repositories.ContactsDbContext
{
    public partial class RekrutacjaNetPcCrudContext : DbContext
    {
        public RekrutacjaNetPcCrudContext()
        {
            this.ChangeTracker.LazyLoadingEnabled = false;
        }

        public RekrutacjaNetPcCrudContext(DbContextOptions<RekrutacjaNetPcCrudContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ContactCategory> ContactCategory { get; set; }
        public virtual DbSet<ContactSubcategory> ContactSubcategory { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<Users> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ContactSubcategory>(entity =>
            {
                entity.HasOne(d => d.Category)
                    .WithMany(p => p.ContactSubcategory)
                    .HasForeignKey(d => d.CategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ContactSubcategory_ContactCategory");
            });

            modelBuilder.Entity<Contacts>(entity =>
            {
                entity.HasOne(d => d.Category)
                    .WithMany(p => p.Contacts)
                    .HasForeignKey(d => d.CategoryId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Contacts_Contacts");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}